server:
  JWT_SECRET: 'test'
  url: "https://example.com"
  hostname: "http://localhost"
  port: 8001

features: 
  login: true
  register: true
  explorer: true
  search: true
  preview: true